[programs.localnet]
solcraft_breeding = "F4FfKsLLJjNR8WB6wpGufabkZFG6McptNuewPFSfKQM1"

[programs.devnet]
solcraft_breeding = "F4FfKsLLJjNR8WB6wpGufabkZFG6McptNuewPFSfKQM1"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet.json"

[scripts]
test_mint = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/mintNFT.ts"
test_init_candy_machine = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/initializeCandyMachine.ts"
test_update_candy_machine = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/updateCandyMachine.ts"
test_breed = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/breed.ts"
