[programs.localnet]
solcraft_breeding = "2gQx7EEfMRNFVFG8NVfvE6KhCDV1RpWGRpcWVHCJJztM"

[programs.devnet]
solcraft_breeding = "2gQx7EEfMRNFVFG8NVfvE6KhCDV1RpWGRpcWVHCJJztM"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/backend.json"

[scripts]
test_init_pig_machine = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/initializePigMachine.ts"
test_breed = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/breed.ts"
test_stake = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/stake.ts"
test_unstake = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/unstake.ts"
log_pig_machine = "npx ts-mocha -p ./tsconfig.json -t 1000000 scripts/logPigMachine.ts"
test_init_runes = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/initializeRunes.ts"
test_mint_tokens = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/mintTokens.ts"
get_rarities = "npx ts-mocha -p ./tsconfig.json -t 100000 tests/getRarities.ts"
